--[[
Copyright (C) Sotin NU aka VirRus77
Author: Sotin NU aka VirRus77
--]]


---@enum
SubCategory = {
    ToolsLevel1 = "ToolsLevel1",
    ToolsLevel2 = "ToolsLevel2",
    BotsHeads = "BotsHeads",
    BotsBodies = "BotsBodies",
    BotsDrives = "BotsDrives",
    BotsUpgrades = "BotsUpgrades",
    PartsWood = "PartsWood",
    PartsStone = "PartsStone",
    PartsClay = "PartsClay",
    PartsMetal = "PartsMetal",
    FoodMushroom = "FoodMushroom",
    FoodPumpkin = "FoodPumpkin",
    FoodBerry = "FoodBerry",
    FoodApple = "FoodApple",
    FoodCereal = "FoodCereal",
    FoodFish = "FoodFish",
    FoodCarrot = "FoodCarrot",
    FoodOther = "FoodOther",
    ClothingWool = "ClothingWool",
    ClothingCotton = "ClothingCotton",
    ClothingRushes = "ClothingRushes",
    ClothingHeadwear = "ClothingHeadwear",
    ClothingOther = "ClothingOther",
    LeisureDoll = "LeisureDoll",
    LeisureHorse = "LeisureHorse",
    LeisureOther = "LeisureOther",
    Medicine = "Medicine",
    Education = "Education",
    Art = "Art",
    WildlifeAnimals = "WildlifeAnimals",
    WildlifeCrops = "WildlifeCrops",
    Vehicles = "Vehicles",
    Misc = "Misc",
    BuildingsWorkshop = "BuildingsWorkshop",
    BuildingsStorage = "BuildingsStorage",
    BuildingsSpecial = "BuildingsSpecial",
    BuildingsFood = "BuildingsFood",
    BuildingsWalls = "BuildingsWalls",
    BuildingsFloors = "BuildingsFloors",
    BuildingsTrains = "BuildingsTrains",
    BuildingsAnimals = "BuildingsAnimals",
    BuildingsClothing = "BuildingsClothing",
    BuildingsMisc = "BuildingsMisc",
    BuildingsDecoration = "BuildingsDecoration",
    BuildingsPrizes = "BuildingsPrizes",
    Hidden = "Hidden",
    Any = "Any",
    Effects = "Effects",
    Prizes = "Prizes",
    Total = "Total",
}